### ISSUE TITLE
功能申请

### ISSUE THREAD

**Issue by gghrgr** [tiansh/yaofang#62]
最近单个微博页面里面底部新增了热门内容推荐，能否隐藏？还有也是单个微博页面里面右侧一排博主的介绍相册什么的能否隐藏？谢谢

**Comment by tiansh** [comment]
相册：界面清理 - 隐藏模块 - 个人主页 - 相册

单条微博（微博正文）页的推荐我晚些时候加，可以暂时用这段 CSS：


```css
/* V6旧版 */
[id^="Pl_Official_WeiboDetail__"] .WB_feed_type ~ .WB_cardwrap,
[id^="Pl_Official_WeiboDetail__"] ~ [id^="Pl_Core_NewMixFeed__"] { display: none !important; }

/* V7新版（需要安装脚本） */
[yawf-component-tag="repost-comment-recom"] { display: none !important; }
```
