### ISSUE TITLE
关于今天强制新增的灰色化

### ISSUE THREAD

**Issue by DCxDESIGN** [tiansh/yaofang#81]
开发者您好，看到您已经提交了灰色化相关的代码改动，想问问应该在哪里调整此项？

另外，看到您代码中灰色相关的内容用了单词 gray 但灰色在微博似乎是 grey 和 gray 混合使用，是否会影响实际效果？

**Comment by tiansh** [comment]
旧版的忘记改了……新版的打开“修改微博显示逻辑以允许相关改造功能”会把首页消息流里面的恢复回来，别的地方没动。有需要可以用如下自定义CSS

```css
.grayTheme, .gn_header, .B_left_nav, .WB_main_c, .WB_main_r .WB_cardwrap, .templete_enter a, .webim_fold_v2, .W_gotop em, .setup_template_new .inner_wrap, .W_layer .content { filter: grayscale(0%) !important; } ​​​
```
